### ISSUE TITLE
Error on line 23

### ISSUE THREAD

**Issue by mcheavens** [priiduonu/uvcfwlinks#1]
File "./getcamfirmware.py", line 23
    print(f"Error fetching data: {e}")
                                    ^
SyntaxError: invalid syntax

**Comment by priiduonu** [comment]
What is your python version? The f-strings were introduced in python 3.6.

If upgrading Python isn't an option, replace the f-string with an older formatting style:

```
print("Error fetching data: {}".format(e))
```

or

```
print("Error fetching data:", e)
```

That also applies to other `print` functions in the script.

**Comment by priiduonu** [comment]
Did you sort it out? May we close the issue?
